fos_elastica:
    clients:
        default: { host: %elasticsearch_host%, port: %elasticsearch_port% }
    serializer:
        callback_class: FOS\ElasticaBundle\Serializer\Callback
        serializer: serializer
    indexes:
        readlater:
            finder: ~
            client: default
            settings:
                number_of_shards: 1
            types:
                bookmarks:
                    _all:
                        enabled: false
                    serializer: ~
                    dynamic_templates:
                        default_string:
                            match_mapping_type: string
                            match: "*"
                            mapping:
                                type: string
                                index: not_analyzed
                                fields:
                                    search:
                                        type: string
                    persistence:
                        elastica_to_model_transformer:
                            query_builder_method: createSearchQueryBuilder
                        driver: orm
                        model: AppBundle\Entity\Bookmark
                        provider: ~
                        listener: ~
                        finder: ~